# Generated by Django 5.1.2 on 2024-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Youtube URL')),
                ('codepen_url', models.URLField(blank=True, verbose_name='Codepen URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
